config/routes.rb
Rails.application.routes.draw do
  get 'tags/index'

  devise_for :users
  resources :ideas
  resources :tags

  get 'about' => 'static#about'

  root 'static#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  belongs_to :publisher

  validates_presence_of :name
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :idea
  belongs_to :user, optional: true
end

app/models/fan.rb
class Fan < ApplicationRecord
  belongs_to :relationship, polymorphic: true
end

app/models/ga_user.rb
class GaUser < ApplicationRecord
  has_many :students, class_name: 'GaUser',
                      foreign_key: 'teacher_id'

  belongs_to :teacher, class_name: 'GaUser',
                       optional: true
end

app/models/idea.rb
class Idea < ApplicationRecord
  mount_uploader :picture, PictureUploader
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :fans, :as => :relationship 
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :authors
  has_many :books, through: :authors
end

app/models/stalk.rb
class Stalk < ApplicationRecord
  belongs_to :stalker, class_name: 'TwitterUser'
  belongs_to :stalkee, class_name: 'TwitterUser'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :ideas
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :fans, :as => :relationship 
end

app/models/twitter_user.rb
class TwitterUser < ApplicationRecord
  has_many :stalkings, class_name: 'Stalk',
                            foreign_key: 'stalker_id'

  has_many :stalked, class_name: 'Stalk',
                            foreign_key: 'stalkee_id'

  has_many :victims, through: :stalkings, source: :stalkee
  has_many :stalkers, through: :stalked, source: :stalker
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @ideas = Idea.all
  end

  def show
  end

  def new
    @idea = Idea.new
  end

  def edit
  end

  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
      @tags = @idea.tags
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage
  end

  def about
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/ideas/_form.html.erb
<%= form_for(idea) do |f| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<% if current_user %>
  <%= link_to 'Show', @idea %> |
  <%= link_to 'Back', ideas_path %>
<% end %>

app/views/ideas/index.html.erb
<% provide(:title, 'Ideas Page') %>

<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td>
          <%= image_tag idea.picture, width: 300 if idea.picture.present? %>
        </td>
        <td>
          <% idea.tags.each do |tag| %>
            <button type="button" class="btn" style="background: <%= tag.color %>">
              <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
              <%= tag.name %>
            </button>
          <% end %>
        </td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @idea.picture %>
</p>

<% if current_user %>
  <%= link_to 'Edit', edit_idea_path(@idea) %> |
  <%= link_to 'Back', ideas_path %>
<% end %>

<div class="container">
  <div class="row">
    <% @tags.each do |tag| %>
    <button type="button" class="btn" style="background: <%= tag.color %>">
      <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
      <%= tag.name %>
    </button>
    <% end %>
  </div>
</div>