config/routes.rb
Rails.application.routes.draw do
  get 'tags/index'

  devise_for :users
  resources :ideas
  resources :tags

  get 'about' => 'static#about'

  root 'static#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  belongs_to :publisher

  validates_presence_of :name
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :idea
  belongs_to :user, optional: true
end

app/models/fan.rb
class Fan < ApplicationRecord
  belongs_to :relationship, polymorphic: true
end

app/models/ga_user.rb
class GaUser < ApplicationRecord
  has_many :students, class_name: 'GaUser',
                      foreign_key: 'teacher_id'

  belongs_to :teacher, class_name: 'GaUser',
                       optional: true
end

app/models/idea.rb
class Idea < ApplicationRecord
  mount_uploader :picture, PictureUploader
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :fans, :as => :relationship 
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :authors
  has_many :books, through: :authors
end

app/models/stalk.rb
class Stalk < ApplicationRecord
  belongs_to :stalker, class_name: 'TwitterUser'
  belongs_to :stalkee, class_name: 'TwitterUser'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :ideas
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :fans, :as => :relationship 
end

app/models/twitter_user.rb
class TwitterUser < ApplicationRecord
  has_many :stalkings, class_name: 'Stalk',
                            foreign_key: 'stalker_id'

  has_many :stalked, class_name: 'Stalk',
                            foreign_key: 'stalkee_id'

  has_many :victims, through: :stalkings, source: :stalkee
  has_many :stalkers, through: :stalked, source: :stalker
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @ideas = Idea.all
  end

  def show
  end

  def new
    @idea = Idea.new
  end

  def edit
  end

  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
      @tags = @idea.tags
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project3Sample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
  </head>

  <body>
    <%= render "partials/navbar" %>

    <div class="container">
      <% if notice %>
      <!-- show the notice -->
      <p class="alert alert-success"><%= notice %></p>
      <% end %>

      <% if alert %>
      <!-- show the alert -->
      <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <div class="container">
        <h1>This is the <%= yield(:title) %></h1>
        <%= yield %>
      </div>
    </div>

    <%= render "partials/footer" %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer>
  <div class="container">
    &copy; Project 3 Sample
  </div>
</footer>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>

<div class="container">
  <%= debug(params) if Rails.env.development? %>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "The Idea App", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if params[:controller] == 'ideas' %>
        <li class="active">
        <% else %>
        <li>
        <% end %>
          <%= link_to "Ideas", ideas_path, class: "active" %>
        </li>
        <% if params[:controller] == 'tags' %>
        <li class="active">
        <% else %>
        <li>
        <% end %>
          <%= link_to "Tags", tags_path, class: "active" %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <!-- true -->
        <li>
          <%= link_to "Edit Profile", edit_user_registration_path %>
        </li>
        <li>
          <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        </li>
        <% else %>
        <li>
          <%= link_to "Log in", new_user_session_path %>
        </li>
        <li>
          <%= link_to "Register", new_user_registration_path %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>